# tag::common[]
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
# end::common[]
#tag::initial[]
      - run: npm install
      - run: npm run lint
#end::initial[]
