[{invert}]
= Docker : Volumes

== 🤔 Quel est le problème ?

* Faut-il fabriquer sa propre image à chaque fois ?
** Ref. copie du `README` pour utiliser `cowsay`

* Comment partager des fichiers entre conteneurs ?

* Et entre hôte et conteneur ?

== Problème des Layers

* ⏱️ Performances : les layers ont de très mauvais performance I/O (disque)

* 💾 Si vous supprimez un conteneur, ses layers disparaissent

* ❌ Pas de partage de layer possible entre conteneurs

== Docker Volumes

* Ce sont des dossier stockés sur l'hôte,
* gérés par le Docker Engine,
* Pouvant être partagés,
* Et survivant aux conteneurs

=> Parfait 🦄

== 🎓 Votre premier volume

* Vérifiez que le dossier `/app` n'existe pas au préalable :
+
[source,bash]
----
docker container run --rm alpine ls -la /app
----

* Essayez maintenant avec un volume :
+
[source,bash]
----
docker volume create app-data
docker container run --rm --volume=app-data:/app alpine ls -la /app
docker volume ls
----

* Essayez de créer un fichier dedans :
+
[source,bash]
----
docker container run --rm --volume=app-data:/app alpine touch /app/test-1
docker container run --rm --volume=app-data:/app alpine ls -la /app
----

== Partager avec l'hôte

* Concept : partager un dossier/fichier de l'hôte
** Contrainte : chemin absolu

* ⚠️ à n'utiliser que pour des commandes "one shot"
** Entorse à la portabilité (file owner, permission, contrainte du chemin)

* 🎓 Dans GitPod, essayez la commande suivante :
+
[source,bash]
----
docker container run --rm --volume /workspace:/app alpine ls -la /app
----

== 🎓 CI : Partager le dépôt dans le conteneur

* Revenons à l'image Docker dans GitHub Actions
* Enlevez la ligne `COPY ./ /app` du workflow
* Utilisez un partage avec l'hôte pour le fichier source `index.js`

* 💡 `--workdir="$(pwd)"`

== ✅ CI : Partager le dépôt dans le conteneur

Dockerfile:

[source,Dockerfile]
----
include::../code-samples/gh-actions/nodejs-Dockerfile[tags="common"]
# Comment the COPY instruction
----

GitHub Workflow:

[source,yaml]
----
# bonjour.yml
name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - run: docker image build --tag="${IMAGE_NAME}" ./
      # Uncomment to validate your work (should fail the next step)
      # - run: echo 'Hello Error' > ./index.js
      - run: docker container run --volume="$(pwd)":"$(pwd)" --workdir="$(pwd)" "${IMAGE_NAME}" npm run lint
----

== 🎓 Sécurité des conteneurs

* *Buts :*
** Limiter l'impact d'un processus malicieux
** S'assurer des meilleurs performances de production
** Obtenir une liste exhaustive des dossier utilisés par l'application

* Essayez d'exécuter un conteneur `webserver-2`, basé sur l'image `nginx`, avec l'option `--read-only` activée
** 💡 Pensez à regarder les logs si le conteneur est en erreur
** 💡 Déclarez un volume pour chaque dossier/fichier nécessitant une écriture

== ✅ Sécurité des conteneurs

[source,bash]
----
docker container run --detach --name=webserver-2 --read-only \
  --volume=/var/cache/nginx --volume=/var/run nginx
----

== Checkpoint 🎯

* Docker sépare le cycle de vie des conteneurs de celui des données
** Utile pour les mises à jours d'images

* Les données des conteneurs peuvent être partagées en utilisant des volumes

* Bonne pratique : utiliser les options de volumes de Docker permet de mieux communiquer les caractéristiques et contraintes de l'application

=> DevOps The Right Way 🦄
